### ISSUE TITLE
Hangs on "empty return"

### ISSUE THREAD

**Issue by Mats-SX** [knutwalker/git-drive#2]
![Screenshot 2020-11-17 at 10 14 06](https://user-images.githubusercontent.com/2419675/99370258-be34e680-28bd-11eb-99bc-965e71bb2687.png)

In the `^C` places I've pressed return but it hung. I expected it was going to use the value shown in brackets.

It does work when I type in the value.

macOS 10.15.6

**Comment by knutwalker** [comment]
Thanks for the report :)
Technically it doesn't hang, the prompt was just waiting for a non-empty input, though I can definitely see how that can be confused with hanging. I've change the ui of those prompts to make it hopefully more apparent what is happening and also added error messages when you want to continue with an empty input, instead of doing nothing.
When you got time, please checkout 0.3.0 https://github.com/knutwalker/git-drive/releases/tag/0.3.0

**Comment by Mats-SX** [comment]
Very nice -- this makes it a lot clearer! Happy to close.
